const examples = [
  {
    model: 'Midjourney',
    style: 'Cinematic',
    imageDesc: 'Mountain landscape at sunset',
    prompt:
      'Dramatic mountain landscape at golden hour, towering granite peaks bathed in warm amber light, low-lying clouds threading through valleys, long shadows across alpine meadows, epic scale, atmospheric perspective, photorealistic --ar 16:9 --v 6.1 --style raw',
    negative: 'flat lighting, oversaturated, tourist photo, power lines, people',
  },
  {
    model: 'Stable Diffusion',
    style: 'Photographic',
    imageDesc: 'Portrait of a woman',
    prompt:
      '(professional portrait photography:1.3) of elegant woman, (soft natural window light:1.2), shallow depth of field, (85mm lens:1.1), warm skin tones, subtle smile, (high-end fashion editorial:1.2), ultra detailed',
    negative: '(deformed:1.4), blurry, watermark, text, ugly, low quality',
  },
  {
    model: 'Flux',
    style: 'Technical',
    imageDesc: 'Modern architecture',
    prompt:
      'Hyperrealistic modern architectural photography, minimalist concrete building with floor-to-ceiling glass facade, precise geometric forms, dramatic overcast diffused lighting, ultra-sharp details, 8K resolution, architectural digest quality',
    negative: 'distorted perspective, lens distortion, people, cars, noise',
  },
  {
    model: 'DALL-E 3',
    style: 'Artistic',
    imageDesc: 'Rainy city street at night',
    prompt:
      'A rain-soaked city street at night captured in the style of a contemporary oil painting, neon reflections shimmering across wet cobblestones, solitary figure beneath a glowing umbrella, impressionistic brushwork, rich jewel tones of cobalt and crimson',
    negative: '',
  },
];

export default function ExamplesSection() {
  return (
    <section
      id="examples"
      className="mx-auto max-w-5xl px-4 py-16 sm:px-6"
      aria-labelledby="examples-heading"
    >
      <h2
        id="examples-heading"
        className="font-grotesk text-2xl font-700 text-[var(--text-primary)] mb-2"
      >
        AI Prompt Examples
      </h2>
      <p className="font-inter text-sm text-[var(--text-secondary)] mb-10">
        Real prompts generated by PromptLens — model-specific syntax included.
      </p>
      <div className="space-y-6">
        {examples.map((ex) => (
          <div
            key={ex.imageDesc}
            className="rounded-2xl border border-[var(--border-subtle)] bg-[var(--bg-card)] p-6"
          >
            <div className="flex flex-wrap items-center gap-2 mb-4">
              <span className="rounded-full border border-[var(--border-subtle)] px-2.5 py-1 font-mono text-[11px] text-[var(--text-secondary)]">
                {ex.model}
              </span>
              <span className="rounded-full border border-[var(--border-subtle)] px-2.5 py-1 font-mono text-[11px] text-[var(--text-secondary)]">
                {ex.style}
              </span>
              <span className="font-inter text-xs text-[var(--text-secondary)]">
                — {ex.imageDesc}
              </span>
            </div>
            <div className="space-y-3">
              <div>
                <p className="font-mono text-[10px] uppercase tracking-wider text-[var(--text-secondary)] mb-1">
                  Main Prompt
                </p>
                <p className="font-mono text-sm text-[var(--text-primary)] leading-relaxed break-words">
                  {ex.prompt}
                </p>
              </div>
              {ex.negative && (
                <div>
                  <p className="font-mono text-[10px] uppercase tracking-wider text-[var(--error)]/70 mb-1">
                    Negative Prompt
                  </p>
                  <p className="font-mono text-sm text-[var(--error)]/80 leading-relaxed">
                    {ex.negative}
                  </p>
                </div>
              )}
            </div>
          </div>
        ))}
      </div>
    </section>
  );
}
