import { useState } from 'react';
import { useTranslation } from 'react-i18next';
import { motion } from 'framer-motion';
import { Copy, Check, Download, RotateCcw } from 'lucide-react';
import type { DescribeImageResult as DescribeResultType } from '../types';

interface Props {
  result: DescribeResultType;
  onReset: () => void;
  onRegenerate: () => void;
}

function CopyButton({ text, label }: { text: string; label: string }) {
  const [copied, setCopied] = useState(false);

  const handleCopy = async () => {
    await navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <button
      onClick={handleCopy}
      className="flex items-center gap-1.5 rounded-lg px-3 py-1.5 font-inter text-xs font-600 transition-all duration-200 hover:scale-[1.02]"
      style={{
        background: copied ? 'rgba(52, 211, 153, 0.15)' : 'var(--bg-elevated)',
        color: copied ? '#34d399' : 'var(--text-secondary)',
        border: `1px solid ${copied ? '#34d39940' : 'var(--border-subtle)'}`,
      }}
      title={`Copy ${label}`}
    >
      {copied ? <Check size={12} /> : <Copy size={12} />}
      {copied ? 'Copied!' : `Copy ${label}`}
    </button>
  );
}

const containerVariants = {
  hidden: { opacity: 0 },
  visible: { opacity: 1, transition: { staggerChildren: 0.08, delayChildren: 0.1 } },
};

const itemVariants = {
  hidden: { opacity: 0, y: 20 },
  visible: { opacity: 1, y: 0, transition: { duration: 0.4, ease: 'easeOut' } },
};

export default function DescribeImageResult({ result, onReset, onRegenerate }: Props) {
  const { t } = useTranslation();

  const handleExport = () => {
    const content = [
      '═══════════════════════════════════════════',
      '  IMAGE DESCRIPTION — ImageToPrompt.dev',
      '═══════════════════════════════════════════',
      '',
      '── Full Description ──',
      result.fullDescription,
      '',
      '── Key Elements ──',
      `Subjects: ${result.keyElements.subjects.join(', ')}`,
      `Objects: ${result.keyElements.objects.join(', ')}`,
      `Setting: ${result.keyElements.setting}`,
      `People: ${result.keyElements.people}`,
      '',
      '── Visual Analysis ──',
      `Colors: ${result.visualAnalysis.dominantColors.join(', ')}`,
      `Lighting: ${result.visualAnalysis.lighting}`,
      `Composition: ${result.visualAnalysis.composition}`,
      `Mood: ${result.visualAnalysis.mood}`,
      '',
      '── Alt Text ──',
      result.altText,
      '',
      '═══════════════════════════════════════════',
      '  Generated by ImageToPrompt.dev',
      '═══════════════════════════════════════════',
    ].join('\n');

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `image-description-${Date.now()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <motion.div
      variants={containerVariants}
      initial="hidden"
      animate="visible"
      className="space-y-5"
    >
      {/* Header */}
      <motion.div
        variants={itemVariants}
        className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-[var(--border-subtle)] bg-[var(--bg-card)] p-4"
      >
        <div className="flex items-center gap-3">
          <span className="text-xl" aria-hidden="true">📝</span>
          <h2 className="font-grotesk text-lg font-700 text-[var(--text-primary)]">
            {t('describe.resultTitle', 'Image Description Ready')}
          </h2>
        </div>
        <div className="flex items-center gap-2">
          <button
            onClick={handleExport}
            className="flex items-center gap-1.5 rounded-lg px-3 py-1.5 font-inter text-xs font-600 transition-all hover:scale-[1.02]"
            style={{ background: 'var(--bg-elevated)', color: 'var(--text-secondary)', border: '1px solid var(--border-subtle)' }}
          >
            <Download size={12} />
            Export
          </button>
          <button
            onClick={onReset}
            className="flex items-center gap-1.5 rounded-lg px-3 py-1.5 font-inter text-xs font-600 transition-all hover:scale-[1.02]"
            style={{ background: 'var(--bg-elevated)', color: 'var(--text-secondary)', border: '1px solid var(--border-subtle)' }}
          >
            <RotateCcw size={12} />
            {t('describe.describeAnother', 'Describe Another')}
          </button>
        </div>
      </motion.div>

      {/* Full Description */}
      <motion.div
        variants={itemVariants}
        className="rounded-2xl border border-[var(--border-subtle)] bg-[var(--bg-card)] p-5"
      >
        <div className="flex items-center justify-between mb-3">
          <h3 className="font-grotesk text-sm font-700 uppercase tracking-wider text-[var(--accent-lens)]">
            {t('describe.fullDescription', 'Full Description')}
          </h3>
          <CopyButton text={result.fullDescription} label="Description" />
        </div>
        <p className="font-inter text-sm leading-relaxed text-[var(--text-primary)] whitespace-pre-wrap">
          {result.fullDescription}
        </p>
      </motion.div>

      {/* Key Elements */}
      <motion.div
        variants={itemVariants}
        className="rounded-2xl border border-[var(--border-subtle)] bg-[var(--bg-card)] p-5"
      >
        <div className="flex items-center justify-between mb-3">
          <h3 className="font-grotesk text-sm font-700 uppercase tracking-wider" style={{ color: '#60a5fa' }}>
            {t('describe.keyElements', 'Key Elements')}
          </h3>
          <CopyButton
            text={`Subjects: ${result.keyElements.subjects.join(', ')}\nObjects: ${result.keyElements.objects.join(', ')}\nSetting: ${result.keyElements.setting}\nPeople: ${result.keyElements.people}`}
            label="Elements"
          />
        </div>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
          <div className="rounded-xl border border-[var(--border-subtle)] bg-[var(--bg-elevated)] p-3">
            <span className="font-inter text-xs font-600 uppercase tracking-wider text-[var(--text-secondary)]">Subjects</span>
            <ul className="mt-1.5 space-y-1">
              {result.keyElements.subjects.map((s, i) => (
                <li key={i} className="font-inter text-sm text-[var(--text-primary)] flex items-start gap-2">
                  <span className="text-[var(--accent-lens)] mt-0.5">•</span> {s}
                </li>
              ))}
            </ul>
          </div>
          <div className="rounded-xl border border-[var(--border-subtle)] bg-[var(--bg-elevated)] p-3">
            <span className="font-inter text-xs font-600 uppercase tracking-wider text-[var(--text-secondary)]">Objects</span>
            <ul className="mt-1.5 space-y-1">
              {result.keyElements.objects.map((o, i) => (
                <li key={i} className="font-inter text-sm text-[var(--text-primary)] flex items-start gap-2">
                  <span className="text-[var(--accent-cyan)] mt-0.5">•</span> {o}
                </li>
              ))}
            </ul>
          </div>
          <div className="rounded-xl border border-[var(--border-subtle)] bg-[var(--bg-elevated)] p-3">
            <span className="font-inter text-xs font-600 uppercase tracking-wider text-[var(--text-secondary)]">Setting</span>
            <p className="mt-1.5 font-inter text-sm text-[var(--text-primary)] leading-relaxed">{result.keyElements.setting}</p>
          </div>
          <div className="rounded-xl border border-[var(--border-subtle)] bg-[var(--bg-elevated)] p-3">
            <span className="font-inter text-xs font-600 uppercase tracking-wider text-[var(--text-secondary)]">People</span>
            <p className="mt-1.5 font-inter text-sm text-[var(--text-primary)] leading-relaxed">{result.keyElements.people}</p>
          </div>
        </div>
      </motion.div>

      {/* Visual Analysis */}
      <motion.div
        variants={itemVariants}
        className="rounded-2xl border border-[var(--border-subtle)] bg-[var(--bg-card)] p-5"
      >
        <div className="flex items-center justify-between mb-3">
          <h3 className="font-grotesk text-sm font-700 uppercase tracking-wider" style={{ color: '#a78bfa' }}>
            {t('describe.visualAnalysis', 'Visual Analysis')}
          </h3>
          <CopyButton
            text={`Colors: ${result.visualAnalysis.dominantColors.join(', ')}\nLighting: ${result.visualAnalysis.lighting}\nComposition: ${result.visualAnalysis.composition}\nMood: ${result.visualAnalysis.mood}`}
            label="Analysis"
          />
        </div>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
          <div className="rounded-xl border border-[var(--border-subtle)] bg-[var(--bg-elevated)] p-3">
            <span className="font-inter text-xs font-600 uppercase tracking-wider text-[var(--text-secondary)]">Dominant Colors</span>
            <div className="mt-2 flex flex-wrap gap-2">
              {result.visualAnalysis.dominantColors.map((color, i) => (
                <span
                  key={i}
                  className="rounded-full px-3 py-1 font-inter text-xs font-500"
                  style={{
                    background: 'var(--bg-card)',
                    color: 'var(--text-primary)',
                    border: '1px solid var(--border-subtle)',
                  }}
                >
                  {color}
                </span>
              ))}
            </div>
          </div>
          <div className="rounded-xl border border-[var(--border-subtle)] bg-[var(--bg-elevated)] p-3">
            <span className="font-inter text-xs font-600 uppercase tracking-wider text-[var(--text-secondary)]">Lighting</span>
            <p className="mt-1.5 font-inter text-sm text-[var(--text-primary)] leading-relaxed">{result.visualAnalysis.lighting}</p>
          </div>
          <div className="rounded-xl border border-[var(--border-subtle)] bg-[var(--bg-elevated)] p-3">
            <span className="font-inter text-xs font-600 uppercase tracking-wider text-[var(--text-secondary)]">Composition</span>
            <p className="mt-1.5 font-inter text-sm text-[var(--text-primary)] leading-relaxed">{result.visualAnalysis.composition}</p>
          </div>
          <div className="rounded-xl border border-[var(--border-subtle)] bg-[var(--bg-elevated)] p-3">
            <span className="font-inter text-xs font-600 uppercase tracking-wider text-[var(--text-secondary)]">Mood</span>
            <p className="mt-1.5 font-inter text-sm text-[var(--text-primary)] leading-relaxed">{result.visualAnalysis.mood}</p>
          </div>
        </div>
      </motion.div>

      {/* Alt Text */}
      <motion.div
        variants={itemVariants}
        className="rounded-2xl border border-[var(--border-subtle)] bg-[var(--bg-card)] p-5"
      >
        <div className="flex items-center justify-between mb-3">
          <h3 className="font-grotesk text-sm font-700 uppercase tracking-wider" style={{ color: '#34d399' }}>
            {t('describe.altText', 'Alt Text')}
          </h3>
          <CopyButton text={result.altText} label="Alt Text" />
        </div>
        <div
          className="rounded-lg p-3"
          style={{ background: 'var(--bg-elevated)', border: '1px solid var(--border-subtle)' }}
        >
          <p className="font-mono text-sm text-[var(--text-primary)] leading-relaxed">
            {result.altText}
          </p>
        </div>
        <p className="mt-2 font-inter text-xs text-[var(--text-secondary)]">
          {t('describe.altTextHint', 'Use this as the alt attribute for <img> tags to improve web accessibility.')}
        </p>
      </motion.div>

      {/* Regenerate button */}
      <motion.div variants={itemVariants} className="flex justify-center pt-2">
        <button
          onClick={onRegenerate}
          className="flex items-center gap-2 rounded-xl px-6 py-2.5 font-inter text-sm font-600 transition-all hover:scale-[1.02]"
          style={{ background: 'var(--bg-elevated)', color: 'var(--text-secondary)', border: '1px solid var(--border-subtle)' }}
        >
          <RotateCcw size={14} />
          {t('describe.regenerate', 'Regenerate Description')}
        </button>
      </motion.div>
    </motion.div>
  );
}
